apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f base.yml
    kompose.version: 1.18.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: local
  name: local
spec:
  ports:
  - name: "7654"
    port: 7654
    targetPort: 7654
  - name: "8085"
    port: 8085
    targetPort: 8085
  - name: "8086"
    port: 8086
    targetPort: 8086
  selector:
    io.kompose.service: local
status:
  loadBalancer: {}
