apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f base.yml
    kompose.version: 1.18.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: local
  name: local
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: local
    spec:
      containers:
      - args:
        - /bin/bash
        image: eu.gcr.io/cognitedata/cloud-emulators:latest
        name: lts-emulators
        ports:
        - containerPort: 7654
        - containerPort: 8085
        - containerPort: 8086
        resources: {}
        tty: true
      restartPolicy: Always
status: {}
